language: objective-c
osx_image: xcode7
env:
  - LC_CTYPE=en_US.UTF-8
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
  - gem install cocoapods xcpretty -N
script:
#  - pod spec lint
  - set -o pipefail && xcodebuild test -scheme Himotoki-Mac | xcpretty -c
notifications:
  email: false
