# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode7
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S" SCHEME="Swinject-iOS" SDK=iphonesimulator9.0
#    - DESTINATION="OS=8.2,name=iPhone 5" SCHEME="Swinject-iOS" SDK=iphonesimulator9.0
#    - DESTINATION="OS=8.3,name=iPhone 5S" SCHEME="Swinject-iOS" SDK=iphonesimulator9.0
#    - DESTINATION="OS=8.4,name=iPhone 6" SCHEME="Swinject-iOS" SDK=iphonesimulator9.0
    - DESTINATION="OS=9.0,name=iPhone 6 Plus" SCHEME="Swinject-iOS" SDK=iphonesimulator9.0
    - DESTINATION="arch=x86_64" SCHEME="Swinject-OSX" SDK=macosx10.11
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - brew update; brew update # Workaround for https://github.com/Homebrew/homebrew/issues/42553
  - brew outdated xctool || brew upgrade xctool
  - brew install carthage
  - carthage version
  - carthage bootstrap --verbose --no-use-binaries --use-submodules
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project Swinject.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  - xcodebuild -project Swinject.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c
